import type { Article } from "@/lib/insights/types";

/**
 * Pillar article for the ai-automation category.
 *
 * SOURCE OF TRUTH. The body is generated verbatim from the author's
 * Markdown source, ArkFlow_AI_Implementation_Blog_Source.md (supplied
 * 18 September 2026). Formatting only: "##" -> h2, "###" -> h3, "* " runs
 * -> ul, the numbered questions -> steps, every other paragraph -> p, and
 * the "---" rules dropped. Arrow sequences ("A -> B -> C") stay as
 * paragraphs because the flow diagram renders one row on desktop and
 * these run to twelve steps. Do not paraphrase the prose here.
 *
 * THE ONLY NON-SOURCE BLOCKS are the two approved contextual CTAs
 * (`type: "cta"`), after Step 5 and after Step 9.
 *
 * THE ONLY TWO WORDING CHANGES TO THE SOURCE (author-approved,
 * 18 September 2026):
 *  1. Step 6 list: "an AI voice agent" -> "voice-based AI assistance".
 *     verify.mjs check 13 forbids presenting "AI Voice Agent" on a public
 *     surface; the rule was not weakened.
 *  2. Singapore sentence: "while AI adoption is growing" -> "while AI
 *     adoption is being measured across Singapore firms". The cited MOM
 *     report is an inaugural snapshot and establishes no growth trend.
 *
 * NOT FROM THE BODY:
 *  - title: the author's full source H1, shown on the page. `seoTitle` is
 *    the shorter search title, used only for metadata.
 *  - faq: questions are framing; every answer sentence is verbatim source
 *    (checked by the generator).
 *  - cta / solution: website conversion elements.
 *
 * EXTERNAL REFERENCES (verified 18 September 2026):
 *  - Federal Reserve Bank of San Francisco — "AI Adoption Among Small
 *    Businesses: Qualitative Insights from the Small Business Credit
 *    Survey", 15 July 2026.
 *  - Google Workspace — AI for small business (customer service, sales
 *    and marketing), AI for project management, and Gemini Notebook
 *    (internal knowledge base).
 *  - Ministry of Manpower — "Inaugural Release of Report on Adoption of
 *    Artificial Intelligence Among Firms", 30 April 2026: 3.8% integrating
 *    into core processes; implementation costs 44.9%, in-house expertise
 *    42.4%, strategy 32.4% (smaller firms). See wording change 2 above.
 *
 * Publishing this article also restores the /insights/ai-automation
 * pillar to the sitemap and lifts its noindex (both derived).
 */
export const article: Article = {
  slug: "how-to-implement-ai-in-your-business",
  title:
    "How to Implement AI in Your Business: A Practical Step-by-Step Guide for Business Owners",
  seoTitle: "How to Implement AI in Your Business: A Step-by-Step Guide",
  description:
    "A practical guide to implementing AI in your business: where to start, how to find the first opportunity, what to keep human, and how to measure the result.",
  category: "ai-automation",
  level: "discovery",
  published: "2026-09-12",
  authorId: "khai",
  blocks: [
    { type: "p", text: "AI is everywhere." },
    { type: "p", text: "You have probably seen businesses using AI to write content, answer customer enquiries, generate images, analyse data, make sales calls, schedule appointments and automate repetitive work." },
    { type: "p", text: "You may have even tried ChatGPT yourself." },
    { type: "p", text: "Maybe you have asked it to write an email." },
    { type: "p", text: "Maybe you have used AI to create a social media post." },
    { type: "p", text: "Maybe someone has told you:" },
    { type: "p", text: "“You need to start using AI in your business.”" },
    { type: "p", text: "And they are probably right." },
    { type: "p", text: "But there is a problem." },
    { type: "p", text: "Most business owners don’t know where to start." },
    { type: "p", text: "There are thousands of AI tools available. New tools appear every week. Some promise to automate your sales. Others promise to replace your customer service team. Others promise to build websites, write content, analyse your business or create AI agents." },
    { type: "p", text: "So the obvious question becomes:" },
    { type: "p", text: "Which AI should I use?" },
    { type: "p", text: "But that may not be the right question." },
    { type: "p", text: "The better question is:" },
    { type: "p", text: "“Where is my business wasting time, losing customers or repeating the same work—and could AI help solve that?”" },
    { type: "p", text: "That is where AI implementation should begin." },

    { type: "h2", id: "ai-implementation-is-not-about-buying-more-ai-tools", text: "AI Implementation Is Not About Buying More AI Tools" },
    { type: "p", text: "One of the biggest mistakes businesses make is starting with the technology." },
    { type: "p", text: "They see a new AI tool." },
    { type: "p", text: "They buy it." },
    { type: "p", text: "They connect it to something." },
    { type: "p", text: "They play around with it for a few weeks." },
    { type: "p", text: "And eventually, nobody uses it." },
    { type: "p", text: "The problem wasn’t necessarily the AI." },
    { type: "p", text: "The problem was that there was no business problem attached to it." },
    { type: "p", text: "AI works best when it is connected to a real process." },
    { type: "p", text: "For example:" },
    { type: "p", text: "A customer sends an enquiry." },
    { type: "p", text: "Someone on your team receives it." },
    { type: "p", text: "They respond." },
    { type: "p", text: "They ask a few questions." },
    { type: "p", text: "They collect information." },
    { type: "p", text: "They check availability." },
    { type: "p", text: "They send a quotation." },
    { type: "p", text: "The customer takes some time to decide." },
    { type: "p", text: "Someone follows up." },
    { type: "p", text: "The customer books." },
    { type: "p", text: "A reminder is sent." },
    { type: "p", text: "The customer pays." },
    { type: "p", text: "After the appointment, someone follows up again." },
    { type: "p", text: "Eventually, the customer comes back." },
    { type: "p", text: "That is a business process." },
    { type: "p", text: "Now imagine identifying the parts of that process that don’t actually require a human being to do manually." },
    { type: "p", text: "That is where AI and automation become useful." },
    { type: "p", text: "Instead of asking:" },
    { type: "p", text: "“What can AI do?”" },
    { type: "p", text: "Start asking:" },
    { type: "p", text: "“What does my business repeatedly do?”" },
    { type: "p", text: "Then ask:" },
    { type: "p", text: "“Which parts of that work need a human, and which parts don’t?”" },
    { type: "p", text: "That change in thinking can completely change how you approach AI." },

    { type: "h2", id: "step-1-start-with-your-business-not-ai", text: "Step 1: Start With Your Business, Not AI" },
    { type: "p", text: "Before buying anything, map out how your business actually works." },
    { type: "p", text: "Take one customer." },
    { type: "p", text: "Follow their journey from the moment they first discover your business until the moment they become a repeat customer." },
    { type: "p", text: "For example:" },
    { type: "p", text: "Google → Website → WhatsApp → Enquiry → Qualification → Quote → Follow-up → Booking → Payment → Appointment → Follow-up → Repeat Purchase" },
    { type: "p", text: "Now look at every stage." },
    { type: "p", text: "Ask yourself:" },
    {
      type: "ul",
      items: [
        "What happens here?",
        "Who is responsible for it?",
        "How long does it take?",
        "Is it done manually?",
        "Does someone have to copy information from one system to another?",
        "Do customers have to wait?",
        "Do leads sometimes get forgotten?",
        "Does someone have to send the same message repeatedly?",
        "Is information stored in different places?",
        "Does the process depend on one particular employee remembering to do something?",
      ],
    },
    { type: "p", text: "This exercise is often more valuable than searching for AI tools." },
    { type: "p", text: "Because once you understand the process, the technology becomes much easier to choose." },

    { type: "h2", id: "step-2-find-the-repetitive-work", text: "Step 2: Find the Repetitive Work" },
    { type: "p", text: "The best place to start with AI is usually not the most complicated part of your business." },
    { type: "p", text: "It is often the boring part." },
    { type: "p", text: "The work your team does over and over again." },
    { type: "p", text: "Think about things such as:" },
    { type: "h3", text: "Customer enquiries" },
    { type: "p", text: "Do you receive the same questions every day?" },
    { type: "p", text: "For example:" },
    {
      type: "ul",
      items: [
        "“How much does this cost?”",
        "“Do you have availability?”",
        "“Where are you located?”",
        "“How long does it take?”",
        "“What is included?”",
        "“Can I reschedule?”",
        "“What happens next?”",
      ],
    },
    { type: "p", text: "If the answers are already known, AI can potentially help handle the first layer of these conversations." },
    { type: "h3", text: "Follow-ups" },
    { type: "p", text: "Does someone have to remember to follow up with people who:" },
    {
      type: "ul",
      items: [
        "requested a quotation?",
        "didn’t respond?",
        "missed an appointment?",
        "haven’t purchased for several months?",
        "expressed interest but never booked?",
      ],
    },
    { type: "p", text: "This is another area where automation can help." },
    { type: "h3", text: "Data entry" },
    { type: "p", text: "Does your team copy information from:" },
    {
      type: "ul",
      items: [
        "WhatsApp into a CRM?",
        "emails into a spreadsheet?",
        "enquiry forms into another system?",
        "booking information into another calendar?",
        "customer information into multiple platforms?",
      ],
    },
    { type: "p", text: "Every time a person has to copy the same information from one place to another, there may be an opportunity to automate the process." },
    { type: "h3", text: "Internal administration" },
    { type: "p", text: "Look at repetitive internal work too." },
    { type: "p", text: "For example:" },
    {
      type: "ul",
      items: [
        "summarising meetings",
        "preparing reports",
        "organising documents",
        "drafting emails",
        "preparing proposals",
        "creating standard documents",
        "answering internal questions",
        "updating customer records",
      ],
    },
    { type: "p", text: "AI is already being used by businesses for productivity, marketing, customer service, communications, analytics and other operational tasks. (Federal Reserve Bank of San Francisco)" },
    { type: "p", text: "The important thing is not to automate everything." },
    { type: "p", text: "The goal is to automate the right things." },

    { type: "h2", id: "step-3-separate-tasks-that-need-people-from-tasks-that-dont", text: "Step 3: Separate Tasks That Need People From Tasks That Don’t" },
    { type: "p", text: "This is one of the most important parts of AI implementation." },
    { type: "p", text: "Not every task should be automated." },
    { type: "p", text: "Some things require judgement." },
    { type: "p", text: "Some require empathy." },
    { type: "p", text: "Some require creativity." },
    { type: "p", text: "Some require a human relationship." },
    { type: "p", text: "Some involve sensitive decisions." },
    { type: "p", text: "And some tasks are simply better when a person handles them." },
    { type: "p", text: "A useful way to think about it is to divide your work into three categories." },
    { type: "h3", text: "Category 1: Human work" },
    { type: "p", text: "These are tasks where human judgement and relationships matter." },
    { type: "p", text: "Examples:" },
    {
      type: "ul",
      items: [
        "complex customer complaints",
        "negotiations",
        "strategic decisions",
        "sensitive conversations",
        "relationship management",
        "important sales conversations",
        "creative direction",
      ],
    },
    { type: "p", text: "Keep these human." },
    { type: "h3", text: "Category 2: AI-assisted work" },
    { type: "p", text: "These are tasks where a person is still involved, but AI can make them faster." },
    { type: "p", text: "Examples:" },
    {
      type: "ul",
      items: [
        "drafting emails",
        "summarising meetings",
        "preparing proposals",
        "analysing information",
        "researching prospects",
        "creating first drafts",
        "preparing reports",
      ],
    },
    { type: "p", text: "AI helps the employee." },
    { type: "p", text: "The employee remains responsible for the final result." },
    { type: "h3", text: "Category 3: Automated work" },
    { type: "p", text: "These are predictable processes that can happen without someone manually doing every step." },
    { type: "p", text: "Examples:" },
    {
      type: "ul",
      items: [
        "sending appointment reminders",
        "sending confirmation messages",
        "routing enquiries",
        "asking qualification questions",
        "updating CRM records",
        "notifying staff",
        "sending follow-up messages",
        "requesting reviews",
        "reactivating old customers",
      ],
    },
    { type: "p", text: "This is where automation can create significant leverage." },

    { type: "h2", id: "step-4-look-at-your-customer-journey", text: "Step 4: Look at Your Customer Journey" },
    { type: "p", text: "One of the biggest opportunities for AI isn’t inside one department." },
    { type: "p", text: "It is between departments and systems." },
    { type: "p", text: "Imagine a customer sends a message on Instagram." },
    { type: "p", text: "Your employee responds." },
    { type: "p", text: "The customer moves to WhatsApp." },
    { type: "p", text: "Someone asks for their details." },
    { type: "p", text: "The information gets written into a spreadsheet." },
    { type: "p", text: "A quotation is sent through email." },
    { type: "p", text: "The customer doesn’t reply." },
    { type: "p", text: "Nobody follows up." },
    { type: "p", text: "Two weeks later, the customer messages again." },
    { type: "p", text: "The employee has to search through old messages to remember what happened." },
    { type: "p", text: "This is not necessarily a people problem." },
    { type: "p", text: "It is often a systems problem." },
    { type: "p", text: "The customer experiences one journey." },
    { type: "p", text: "Your business experiences five or six disconnected systems." },
    { type: "p", text: "That gap creates friction." },
    { type: "p", text: "And friction creates lost opportunities." },
    { type: "p", text: "AI becomes much more powerful when it is connected to the systems already running your business." },
    { type: "p", text: "For example:" },
    { type: "p", text: "Customer enquiry → AI response → Qualification → CRM → Booking → Confirmation → Reminder → Payment → Follow-up" },
    { type: "p", text: "Instead of treating each step as a separate task, you can start designing it as one connected customer journey." },
    { type: "p", text: "That is the real opportunity." },

    { type: "h2", id: "step-5-choose-one-problem-to-solve-first", text: "Step 5: Choose One Problem to Solve First" },
    { type: "p", text: "You do not need to transform your entire company overnight." },
    { type: "p", text: "In fact, you probably shouldn’t." },
    { type: "p", text: "Start with one problem." },
    { type: "p", text: "For example:" },
    { type: "p", text: "“Our team takes too long to respond to enquiries.”" },
    { type: "p", text: "Or:" },
    { type: "p", text: "“We get lots of leads but don’t follow up consistently.”" },
    { type: "p", text: "Or:" },
    { type: "p", text: "“Our staff spends too much time answering repetitive questions.”" },
    { type: "p", text: "Or:" },
    { type: "p", text: "“Customers frequently forget their appointments.”" },
    { type: "p", text: "Or:" },
    { type: "p", text: "“Our sales team spends too much time doing administrative work.”" },
    { type: "p", text: "Pick one." },
    { type: "p", text: "Then define what success looks like." },
    { type: "p", text: "For example:" },
    { type: "p", text: "“We want every new enquiry to receive an initial response within five minutes.”" },
    { type: "p", text: "Or:" },
    { type: "p", text: "“We want every quotation to receive an appropriate follow-up automatically.”" },
    { type: "p", text: "Or:" },
    { type: "p", text: "“We want our staff to spend less time answering repetitive questions.”" },
    { type: "p", text: "This is important because AI implementation should have a measurable outcome." },
    { type: "p", text: "Otherwise, you may end up with something impressive that doesn’t actually improve the business." },
    { type: "cta", text: "If you know something in your business needs fixing but aren't sure whether AI, automation, or a better-connected workflow is the right answer, start with the problem." },

    { type: "h2", id: "step-6-pick-the-right-ai-tool-for-the-job", text: "Step 6: Pick the Right AI Tool for the Job" },
    { type: "p", text: "Only after identifying the problem should you start looking at technology." },
    { type: "p", text: "You might need:" },
    {
      type: "ul",
      items: [
        "an AI chatbot",
        "a CRM",
        "workflow automation",
        "voice-based AI assistance",
        "an AI assistant",
        "document intelligence",
        "data analysis",
        "email automation",
        "appointment automation",
        "a knowledge base",
        "an integration between existing software",
        "or a combination of several technologies",
      ],
    },
    { type: "p", text: "Notice something important." },
    { type: "p", text: "The answer isn’t always:" },
    { type: "p", text: "“Buy an AI tool.”" },
    { type: "p", text: "Sometimes the answer is:" },
    { type: "p", text: "“Connect the tools you already have.”" },
    { type: "p", text: "Your business may already have a website, CRM, WhatsApp, email, calendar, payment system and accounting software." },
    { type: "p", text: "The problem may simply be that none of them are talking to each other." },
    { type: "p", text: "This is why choosing software before understanding your workflow can create more complexity instead of less." },

    { type: "h2", id: "step-7-give-ai-the-right-information", text: "Step 7: Give AI the Right Information" },
    { type: "p", text: "AI is only as useful as the information and instructions behind it." },
    { type: "p", text: "If you want an AI assistant to speak to your customers, it needs to understand your business." },
    { type: "p", text: "That may include:" },
    {
      type: "ul",
      items: [
        "your services",
        "your pricing",
        "your operating hours",
        "your policies",
        "your frequently asked questions",
        "your target customers",
        "your brand voice",
        "your booking rules",
        "your cancellation policy",
        "your escalation process",
        "your service areas",
        "your customer journey",
      ],
    },
    { type: "p", text: "For example, you wouldn’t want an AI assistant to simply answer:" },
    { type: "p", text: "“Yes, we can help.”" },
    { type: "p", text: "You want it to understand what the customer actually needs." },
    { type: "p", text: "A good AI system should know when to:" },
    { type: "p", text: "Answer → Ask → Qualify → Recommend → Book → Escalate" },
    { type: "p", text: "That is much more useful than simply having an AI that generates text." },

    { type: "h2", id: "step-8-build-the-human-handover", text: "Step 8: Build the Human Handover" },
    { type: "p", text: "Good AI does not mean removing humans from the business." },
    { type: "p", text: "It means allowing humans to spend more time on the work where they create the most value." },
    { type: "p", text: "Your AI should know when it needs to hand a conversation to a person." },
    { type: "p", text: "For example:" },
    { type: "p", text: "“I can help you with the basic information. Let me connect you with our team so they can assist with your specific situation.”" },
    { type: "p", text: "That handover should be designed intentionally." },
    { type: "p", text: "The employee should also receive the conversation history." },
    { type: "p", text: "They shouldn’t have to ask the customer:" },
    { type: "p", text: "“Can you explain what happened?”" },
    { type: "p", text: "again." },
    { type: "p", text: "The system should already tell them:" },
    {
      type: "ul",
      items: [
        "who the customer is",
        "what they asked",
        "what the AI discussed",
        "what information was collected",
        "what stage they are at",
        "what action needs to happen next",
      ],
    },
    { type: "p", text: "This is where AI becomes a business system rather than just a chatbot." },

    { type: "h2", id: "step-9-connect-ai-to-your-existing-systems", text: "Step 9: Connect AI to Your Existing Systems" },
    { type: "p", text: "This is where many businesses underestimate the work involved." },
    { type: "p", text: "An AI assistant sitting by itself can only do so much." },
    { type: "p", text: "Imagine someone asks:" },
    { type: "p", text: "“Do you have an appointment available tomorrow?”" },
    { type: "p", text: "If your AI doesn’t have access to your booking system, it can’t actually check." },
    { type: "p", text: "It can only say:" },
    { type: "p", text: "“Our team will get back to you.”" },
    { type: "p", text: "That’s not much better than having no AI." },
    { type: "p", text: "But if your systems are connected, the process can become:" },
    { type: "p", text: "Customer asks → AI checks availability → AI offers available times → Customer chooses → Booking is created → Confirmation is sent → Reminder is scheduled" },
    { type: "p", text: "Now the AI is actually participating in the business process." },
    { type: "p", text: "The same principle applies to sales, payments, customer records and follow-up." },
    { type: "p", text: "The more relevant systems are connected, the more useful the automation becomes." },
    { type: "cta", text: "AI becomes much more useful when it is connected to the systems your business already relies on." },

    { type: "h2", id: "step-10-test-everything-before-you-let-ai-speak-to-customers", text: "Step 10: Test Everything Before You Let AI Speak to Customers" },
    { type: "p", text: "This step is easy to overlook." },
    { type: "p", text: "Before launching an AI system, test it." },
    { type: "p", text: "Test normal questions." },
    { type: "p", text: "Test unusual questions." },
    { type: "p", text: "Test wrong information." },
    { type: "p", text: "Test angry customers." },
    { type: "p", text: "Test customers who change their minds." },
    { type: "p", text: "Test customers who ask something outside the AI’s knowledge." },
    { type: "p", text: "Test situations where the AI needs a human." },
    { type: "p", text: "Test what happens when the booking system is unavailable." },
    { type: "p", text: "Test what happens when someone sends incomplete information." },
    { type: "p", text: "You should also make sure the system does not confidently invent information." },
    { type: "p", text: "A business should never sacrifice accuracy simply because an AI response sounds professional." },
    { type: "p", text: "The goal is not:" },
    { type: "p", text: "“Make the AI sound intelligent.”" },
    { type: "p", text: "The goal is:" },
    { type: "p", text: "“Make the business process work reliably.”" },

    { type: "h2", id: "step-11-measure-the-results", text: "Step 11: Measure the Results" },
    { type: "p", text: "Once your AI system is live, don’t just ask:" },
    { type: "p", text: "“Is the AI working?”" },
    { type: "p", text: "Ask:" },
    { type: "p", text: "“Is the business performing better?”" },
    { type: "p", text: "Depending on what you implemented, you could measure:" },
    { type: "h3", text: "Sales" },
    {
      type: "ul",
      items: [
        "number of enquiries",
        "qualified leads",
        "bookings",
        "conversion rate",
        "response-to-booking rate",
        "revenue generated",
      ],
    },
    { type: "h3", text: "Customer service" },
    {
      type: "ul",
      items: [
        "response time",
        "unanswered enquiries",
        "customer satisfaction",
        "number of conversations handled",
        "escalation rate",
      ],
    },
    { type: "h3", text: "Operations" },
    {
      type: "ul",
      items: [
        "hours saved",
        "manual tasks reduced",
        "errors reduced",
        "administrative workload",
        "staff productivity",
      ],
    },
    { type: "h3", text: "Retention" },
    {
      type: "ul",
      items: [
        "repeat bookings",
        "follow-up completion",
        "reactivation rate",
        "review requests",
        "customer return rate",
      ],
    },
    { type: "p", text: "AI adoption should ultimately be connected to business outcomes." },
    { type: "p", text: "Not the number of prompts someone has written." },
    { type: "p", text: "Not the number of AI tools the company has purchased." },
    { type: "p", text: "Not how impressive the demo looks." },
    { type: "p", text: "Business results are what matter." },

    { type: "h2", id: "the-biggest-mistake-trying-to-automate-everything", text: "The Biggest Mistake: Trying to Automate Everything" },
    { type: "p", text: "When business owners discover what AI can do, there is a temptation to automate everything immediately." },
    { type: "p", text: "Don’t." },
    { type: "p", text: "You don’t need an AI employee for every department." },
    { type: "p", text: "You don’t need ten different AI tools." },
    { type: "p", text: "You don’t need to rebuild your entire business." },
    { type: "p", text: "You need to identify the few places where AI can make the biggest difference." },
    { type: "p", text: "A simple framework is:" },
    { type: "p", text: "Find the bottleneck." },
    { type: "p", text: "Where is work getting stuck?" },
    { type: "p", text: "Find the repetition." },
    { type: "p", text: "What does your team do again and again?" },
    { type: "p", text: "Find the delay." },
    { type: "p", text: "Where are customers waiting?" },
    { type: "p", text: "Find the leakage." },
    { type: "p", text: "Where are enquiries, opportunities or customers being lost?" },
    { type: "p", text: "Find the connection." },
    { type: "p", text: "Which systems should be talking to each other but aren’t?" },
    { type: "p", text: "Automate the right part." },
    { type: "p", text: "Then measure what changed." },
    { type: "p", text: "That is a much better starting point than buying whatever AI tool is trending this month." },

    { type: "h2", id: "so-where-should-your-business-start", text: "So, Where Should Your Business Start?" },
    { type: "p", text: "If you’re completely new to AI, start with these five questions." },
    {
      type: "steps",
      items: [
        {
          label: "Where does my team spend too much time?",
          text: "Look for repetitive administrative work.",
        },
        {
          label: "Where do customers have to wait?",
          text: "Look at enquiries, bookings, quotations and support.",
        },
        {
          label: "Where are leads falling through the cracks?",
          text: "Look at unanswered messages, missed follow-ups and forgotten enquiries.",
        },
        {
          label: "Where are people copying information between systems?",
          text: "This is often a strong automation opportunity.",
        },
        {
          label: "What would I fix first if I had one extra employee?",
          text: "This is perhaps the most useful question of all.",
        },
      ],
    },
    { type: "p", text: "Imagine you could hire someone whose only job was to handle one repetitive part of your business." },
    { type: "p", text: "What would you give them?" },
    { type: "p", text: "Answering enquiries?" },
    { type: "p", text: "Following up with leads?" },
    { type: "p", text: "Booking appointments?" },
    { type: "p", text: "Sending reminders?" },
    { type: "p", text: "Updating the CRM?" },
    { type: "p", text: "Chasing payments?" },
    { type: "p", text: "Reactivating old customers?" },
    { type: "p", text: "Once you know the answer, you have probably found your first AI opportunity." },

    { type: "h2", id: "you-dont-need-to-become-an-ai-expert", text: "You Don’t Need to Become an AI Expert" },
    { type: "p", text: "This is probably the most important thing to understand." },
    { type: "p", text: "You don’t need to know how to build an AI model." },
    { type: "p", text: "You don’t need to understand APIs." },
    { type: "p", text: "You don’t need to learn how to code." },
    { type: "p", text: "You don’t need to test every AI platform on the market." },
    { type: "p", text: "You are the business owner." },
    { type: "p", text: "Your job is to understand your customers, your team and your business." },
    { type: "p", text: "The technology should serve that business." },
    { type: "p", text: "And this is where professional AI implementation can make sense." },
    { type: "p", text: "Because implementing AI properly is not simply about connecting ChatGPT to your website." },
    { type: "p", text: "Someone needs to understand:" },
    { type: "p", text: "How your business works → where the problems are → what should be automated → what should stay human → what systems need to connect → how the AI should behave → how the workflow should operate → how the results should be measured." },
    { type: "p", text: "That is a completely different service from simply selling you an AI tool." },

    { type: "h2", id: "think-of-ai-as-a-system-not-a-tool", text: "Think of AI as a System, Not a Tool" },
    { type: "p", text: "The businesses that get the most value from AI are not necessarily the businesses with the most AI tools." },
    { type: "p", text: "They are the businesses that understand how their work flows." },
    { type: "p", text: "Think about your business as a journey." },
    { type: "p", text: "A customer discovers you." },
    { type: "p", text: "They reach out." },
    { type: "p", text: "You respond." },
    { type: "p", text: "You understand what they need." },
    { type: "p", text: "You help them make a decision." },
    { type: "p", text: "They book." },
    { type: "p", text: "They pay." },
    { type: "p", text: "You deliver the service." },
    { type: "p", text: "You follow up." },
    { type: "p", text: "They come back." },
    { type: "p", text: "AI can potentially support different parts of that journey." },
    { type: "p", text: "But the real value comes from connecting those parts." },
    { type: "p", text: "One enquiry should not become five disconnected conversations." },
    { type: "p", text: "One customer should not exist as five different records." },
    { type: "p", text: "One booking should not require three people to remember what happens next." },
    { type: "p", text: "One quotation should not disappear simply because someone forgot to follow up." },
    { type: "p", text: "The goal is to build a system where the right information moves to the right place at the right time." },
    { type: "p", text: "And your team can focus on the parts that actually require people." },

    { type: "h2", id: "the-future-of-ai-in-business-isnt-more-tools", text: "The Future of AI in Business Isn’t More Tools" },
    { type: "p", text: "It is better systems." },
    { type: "p", text: "AI is becoming easier to access." },
    { type: "p", text: "Small businesses can now use technology that previously required large teams and expensive infrastructure. Google, for example, highlights use cases ranging from customer service and sales to marketing, project management and internal knowledge management. (Google Workspace)" },
    { type: "p", text: "But access to AI does not automatically create business value." },
    { type: "p", text: "The difficult part is implementation." },
    { type: "p", text: "Singapore’s 2026 data makes this particularly clear: while AI adoption is being measured across Singapore firms, meaningful integration into core processes remains relatively limited, with businesses citing implementation costs, expertise gaps and strategy as significant barriers. (Ministry of Manpower Singapore)" },
    { type: "p", text: "That means the opportunity isn’t simply to find another AI tool." },
    { type: "p", text: "The opportunity is to take the technology that already exists and apply it intelligently to the way your business actually operates." },

    { type: "h2", id: "if-you-dont-know-where-to-start-start-with-your-workflow", text: "If You Don’t Know Where to Start, Start With Your Workflow" },
    { type: "p", text: "You don’t need to begin by asking:" },
    { type: "p", text: "“Which AI should I buy?”" },
    { type: "p", text: "Start with:" },
    { type: "p", text: "“Where is my business losing time, money or opportunities?”" },
    { type: "p", text: "Then work backwards." },
    { type: "p", text: "Find the problem." },
    { type: "p", text: "Map the process." },
    { type: "p", text: "Identify the repetitive work." },
    { type: "p", text: "Decide what should remain human." },
    { type: "p", text: "Identify what can be assisted by AI." },
    { type: "p", text: "Identify what can be automated." },
    { type: "p", text: "Connect the systems." },
    { type: "p", text: "Test the workflow." },
    { type: "p", text: "Measure the result." },
    { type: "p", text: "Then improve it." },
    { type: "p", text: "That’s how you turn AI from an interesting technology into something that actually contributes to your business." },

    { type: "h2", id: "ready-to-find-your-first-ai-opportunity", text: "Ready to Find Your First AI Opportunity?" },
    { type: "p", text: "If you have been thinking about implementing AI in your business but don’t know where to start, you don’t necessarily need another software subscription." },
    { type: "p", text: "You may need someone to look at the way your business currently works and identify where AI and automation can actually make a difference." },
    { type: "p", text: "At ArkFlow, we look at the entire customer journey rather than treating AI as another standalone tool." },
    { type: "p", text: "That can include the journey from:" },
    { type: "p", text: "Enquiry → Conversation → Qualification → Booking → Payment → Follow-up → Repeat Customer" },
    { type: "p", text: "The objective isn’t to add technology for the sake of technology." },
    { type: "p", text: "It’s to connect the systems you already use, remove unnecessary manual work, respond to customers faster, and create a process that can continue working even when your team is busy." },
    { type: "p", text: "If you’re not sure where AI would actually make sense in your business, that’s exactly where the conversation should start." },
    { type: "p", text: "Don’t start by buying AI." },
    { type: "p", text: "Start by understanding your business." },
    { type: "p", text: "Then build the AI around it." },
  ],

  faq: [
    {
      q: "Which AI should I use?",
      a: "Only after identifying the problem should you start looking at technology. Sometimes the answer is: “Connect the tools you already have.”",
    },
    {
      q: "Where should my business start with AI?",
      a: "Start with one problem. Then define what success looks like. This is important because AI implementation should have a measurable outcome.",
    },
    {
      q: "Do I need to become an AI expert?",
      a: "You don’t need to know how to build an AI model. You don’t need to understand APIs. You don’t need to learn how to code. Your job is to understand your customers, your team and your business.",
    },
    {
      q: "Should I automate everything?",
      a: "The important thing is not to automate everything. The goal is to automate the right things.",
    },
    {
      q: "How should I measure whether AI is working?",
      a: "Once your AI system is live, don’t just ask: “Is the AI working?” Ask: “Is the business performing better?” AI adoption should ultimately be connected to business outcomes.",
    },
  ],

  /**
   * This article's own closing framing (Article["cta"]). The shared
   * level-based default frames the close around the Revenue Leak Audit;
   * this article states its own. The primary action is unchanged: the
   * canonical booking modal.
   */
  cta: {
    title: "Not sure where AI would actually make sense in your business?",
    body: "Start with the workflow, not another software subscription. We'll look at how your business currently handles enquiries, customers and follow-up, then identify where a connected revenue system could create useful leverage.",
  },

  solution: {
    label: "See how the journey connects",
    href: "/solutions",
    note: "The goal is to build a system where the right information moves to the right place at the right time.",
  },

  related: ["why-speed-to-lead-matters", "what-is-an-ai-voice-agent"],
};
